CREATE TABLE TB_TRACKING_SENSOR (
    COD_TRACKING_SENSOR BIGSERIAL PRIMARY KEY,
    COD_VEHICLE BIGINT NOT NULL,
    COD_SENSOR VARCHAR(36) NOT NULL,
    TXT_DATA VARCHAR(255) NOT NULL,
    DTH_TRACKING TIMESTAMP NOT NULL
);

CREATE TABLE TB_TRACKING_LOCATION (
    COD_TRACKING_LOCATION BIGSERIAL PRIMARY KEY,
    COD_VEHICLE BIGINT NOT NULL,
    NUM_LATITUDE NUMERIC(10,7) NOT NULL,
    NUM_LONGITUDE NUMERIC(10,7) NOT NULL,
    DTH_TRACKING TIMESTAMP NOT NULL
);